### ISSUE TITLE
Processor: DotNetURLProvider: Error: Unable to find .DotNet status.

### ISSUE THREAD

**Issue by mpanighetti** [autopkg/gerardkok-recipes#249]
Verbose output while attempting to run com.github.gerardkok.download.DotNetSDK with default values:

```
DotNetURLProvider
{'Input': {'language_code': 'en-us', 'release': 'LTS'}}
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "~/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes/DotNet/DotNetURLProvider.py", line 88, in main
    self.env["release_url"] = self.release_url(release, url_path)
  File "~/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes/DotNet/DotNetURLProvider.py", line 81, in release_url
    return f"{BASE_URL}/{url_path}/{self.release(release, url_path)}"
  File "~/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes/DotNet/DotNetURLProvider.py", line 76, in release
    return self.status_release(status, url_path)
  File "~/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes/DotNet/DotNetURLProvider.py", line 62, in status_release
    raise ProcessorError('Unable to find .DotNet status.')
autopkglib.ProcessorError: Unable to find .DotNet status.
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
Unable to find .DotNet status.
Failed.
Receipt written to ~/Library/AutoPkg/Cache/com.github.gerardkok.download.DotNetSDK/receipts/com.github.gerardkok.download-receipt-20240912-225431.plist

The following recipes failed:
    com.github.gerardkok.download.DotNetSDK
        Error in com.github.gerardkok.download.DotNetSDK: Processor: DotNetURLProvider: Error: Unable to find .DotNet status.

Nothing downloaded, packaged or imported.
```

**Comment by mpanighetti** [comment]
No longer seeing this issue.
